mutation AddTrafficData($congestion: Float!, $location: String!) @auth(level: USER) {
  trafficData_insert(data: { congestion: $congestion, location: $location }) {
    id
    timestamp
    congestion
    location
  }
}