query ListTrafficData @auth(level: PUBLIC) {
  trafficData {
    id
    timestamp
    congestion
    location
  }
}

query GetTrafficDataByLocation($location: String!) @auth(level: PUBLIC) {
  trafficData(where: { location: { eq: $location } }) {
    id
    timestamp
    congestion
    location
  }
}